openapi: 3.0.2
info:
  version: 1.0.0
  title: ISM Password Manager API
  contact:
    email: deacudavid21@stud.ase.ro
    url: https://www.linkedin.com/in/david-theodor-deacu-517a951a7/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This API is capable of fetching encrypted information from the server.
tags:
  - name: authentication
    description: Operations about authentication
  - name: accounts
    description: Operations about accounts
servers:
  - url: https://password-manager-api.us-e2.cloudhub.io/v1
paths:
  /actions/auth:
    post:
      summary: Do authentication
      operationId: DoAuth
      tags:
        - authentication
      description: >
        Authenticate the client based on its client-id and client-secret
        credentials.


        Generates a Bearer token that proves user`s identity for further
        requests.


        Responses:


        | HTTP Status | Response Type         |
        Description                                 |

        |-------------|-----------------------|---------------------------------------------|

        | 200         | OK                    | Request was
        successful                      |

        | 401         | Unauthorized          | Invalid client
        credentials                  |

        | 401         | Unauthorized          | Missing or invalid access
        token             |

        | 401         | Unauthorized          | Expired access
        token                        |

        | 401         | Unauthorized          | Revoked access
        token                        |

        | 429         | Too Many Requests     | Request was rejected due to rate
        limitation |

        | 500         | Internal Server Error | Server
        error                                |
      parameters:
        - $ref: '#/components/parameters/BasicAuthorization'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DoAuthRequest'
      responses:
        '200':
          $ref: '#/components/responses/DoAuthResponse'
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      externalDocs:
        url: >-
          https://mermaid.live/?source=https://raw.githubusercontent.com/Dvd134/password-manager-oas/main/sequencediagrams/auth.md
  /accounts:
    get:
      summary: Get accounts
      operationId: GetAccounts
      tags:
        - accounts
      description: >
        Retrieves user accounts.


        Results may be filtered based on a website domain.


        Responses:


        | HTTP Status | Response Type         |
        Description                                 |

        |-------------|-----------------------|---------------------------------------------|

        | 200         | OK                    | Request was
        successful                      |

        | 401         | Unauthorized          | Invalid client
        credentials                  |

        | 401         | Unauthorized          | Missing or invalid access
        token             |

        | 401         | Unauthorized          | Expired access
        token                        |

        | 401         | Unauthorized          | Revoked access
        token                        |

        | 429         | Too Many Requests     | Request was rejected due to rate
        limitation |

        | 500         | Internal Server Error | Server
        error                                |
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
        - $ref: '#/components/parameters/Domain'
        - $ref: '#/components/parameters/ReturnFullResponse'
      responses:
        '200':
          $ref: '#/components/responses/GetAccountsResponse'
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
      externalDocs:
        url: >-
          https://mermaid.live/?source=https://raw.githubusercontent.com/Dvd134/password-manager-oas/main/sequencediagrams/auth.md
    post:
      summary: Do account
      operationId: DoAccount
      tags:
        - accounts
      description: >
        Adds a new account entry in the user accounts list.


        If user(client id) has no associated accounts file, a new one will be
        created.


        Responses:


        | HTTP Status | Response Type         |
        Description                                 |

        |-------------|-----------------------|---------------------------------------------|

        | 201         | Created               | New resource was
        created                    |

        | 401         | Unauthorized          | Invalid client
        credentials                  |

        | 401         | Unauthorized          | Missing or invalid access
        token             |

        | 401         | Unauthorized          | Expired access
        token                        |

        | 401         | Unauthorized          | Revoked access
        token                        |

        | 429         | Too Many Requests     | Request was rejected due to rate
        limitation |

        | 500         | Internal Server Error | Server
        error                                |
      parameters:
        - $ref: '#/components/parameters/BearerAuthorization'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DoAccountRequest'
      responses:
        '201':
          $ref: '#/components/responses/201'
        '401':
          $ref: '#/components/responses/401'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'
components:
  parameters:
    BasicAuthorization:
      name: Authorization
      description: >
        Represents the Basic authentication scheme which uses a Base64-encoded
        string of the client_id and client_secret as the value of the
        Authorization header. 


        The format of the Authorization header is:


        Authorization: Basic [base64-encoded-string]


        The <base64-encoded-string> value should be constructed by concatenating
        the client_id and client_secret values with a colon : separator, then
        Base64-encoding the resulting string.
      in: header
      required: true
      schema:
        type: string
        example: Basic bXljbGllbnQ6bXlzZWNyZXQ=
    BearerAuthorization:
      name: Authorization
      description: |
        Represents the OAuth 2.0 authentication scheme 
      in: header
      required: true
      schema:
        type: string
        example: >-
          Bearer
          eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    Domain:
      name: domain
      description: filters the response on specific website domain.
      in: query
      required: false
      schema:
        type: string
      example: github.com
    ReturnFullResponse:
      name: return_full_response
      description: Fetch optional fields in response.
      in: query
      required: false
      schema:
        type: boolean
        default: false
  schemas:
    DoAuthRequest:
      type: object
      required:
        - passphrase
      properties:
        passphrase:
          type: string
          description: >-
            Additional password that needs to be sent along with the client
            credentials.
      example:
        passphrase: securePassw0rd123!
    MetaResponse:
      type: object
      properties:
        meta:
          type: object
          required:
            - status
          properties:
            status:
              description: |
                Defines response status
              type: string
              enum:
                - succeeded
                - partially_succeeded
                - failed
              example: succeeded
            messages:
              type: array
              items:
                type: object
                required:
                  - code
                  - level
                properties:
                  code:
                    type: string
                    description: |
                      Unique technical code of the message
                  text:
                    type: string
                    description: |
                      Optional text to provide human readable information
                  level:
                    type: string
                    description: |
                      Severity level of a message
                    enum:
                      - info
                      - warn
                      - error
    Token:
      type: object
      required:
        - access_token
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
          description: The Bearer token which is used to access the API.
        token_type:
          type: string
          description: The token type.
        expires_in:
          type: integer
          description: The token validity in seconds.
    Account:
      type: object
      required:
        - username
        - password
      properties:
        id:
          type: number
          description: Unique identifier.
        username:
          type: string
          description: Login username.
        password:
          type: string
          description: Login password.
        tags:
          type: array
          items:
            type: string
          description: List of key words used to filter accounts.
        domain:
          type: string
          description: Website linked to an account.
    DoAccountRequest:
      type: object
      required:
        - username
        - password
        - domain
      properties:
        username:
          type: string
          description: Login username.
        password:
          type: string
          description: Login password.
        tags:
          type: array
          items:
            type: string
          description: List of key words used to filter accounts.
        domain:
          type: string
          description: Website linked to an account.
  responses:
    '201':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MetaResponse'
          example:
            meta:
              status: succeeded
              messages:
                - code: Created
                  text: New resource was created
                  level: info
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MetaResponse'
          examples:
            InvalidClientCredentials:
              value:
                meta:
                  status: failed
                  messages:
                    - code: Unauthorized
                      text: Invalid client credentials
                      level: error
            MissingOrInvalidAccessToken:
              value:
                meta:
                  status: failed
                  messages:
                    - code: Unauthorized
                      text: Missing or invalid access token
                      level: error
            ExpiredAccessToken:
              value:
                meta:
                  status: failed
                  messages:
                    - code: Unauthorized
                      text: Expired access token
                      level: error
            RevokedAccessToken:
              value:
                meta:
                  status: failed
                  messages:
                    - code: Unauthorized
                      text: Revoked access token
                      level: error
    '429':
      description: Allowed number of requests exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MetaResponse'
          example:
            meta:
              status: failed
              messages:
                - code: Too Many Requests
                  text: Request was rejected due to rate limitation
                  level: error
    '500':
      description: Something went wrong on server side
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MetaResponse'
          example:
            meta:
              status: failed
              messages:
                - code: Internal Server Error
                  text: Server error
                  level: error
    DoAuthResponse:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/MetaResponse'
              - type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Token'
          example:
            meta:
              status: succeeded
              messages:
                - code: OK
                  text: Request was successful
                  level: info
            data:
              access_token: >-
                eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
              token_type: Bearer
              expires_in: 86400
    GetAccountsResponse:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/MetaResponse'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'
          example:
            meta:
              status: succeeded
              messages:
                - code: OK
                  text: Request was successful
                  level: info
            data:
              - id: 1
                username: username@email.com
                password: securePassw0rd123!
                tags:
                  - github
                  - personal
                domain: github.com
              - id: 2
                username: testUsername@gmail.com
                password: Passw0rd123!
                tags:
                  - gmail
                  - mail
                  - personal
                domain: mail.google.com
